### ISSUE TITLE
Unable to launch plasma client. Error: Cannot read property 'transactionSigner' of undefined

### ISSUE THREAD

**Issue by desimira** [plasma-group/plasma-client#9] opened 2019-03-07 09:07 UTC
Hi there! I've successfully installed plasma client but unfortunately I am unable to connect to Plasma chain. Following the guideline, when I run in terminal ```plasma-client``` I get into this error:
```
Desimiras-MBP:Projects desimiramitkova$ plasma-client
/Users/desimiramitkova/.npm-global/lib/node_modules/plasma-client/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:184
    _this.transactionSigner = options.transactionSigner;
                                      ^

TypeError: Cannot read property 'transactionSigner' of undefined
    at new Accounts (/Users/desimiramitkova/.npm-global/lib/node_modules/plasma-client/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:184:39)
    at new Accounts$$1 (/Users/desimiramitkova/.npm-global/lib/node_modules/plasma-client/node_modules/web3-eth-accounts/dist/web3-eth-accounts.cjs.js:472:10)
    at Object.<anonymous> (/Users/desimiramitkova/.npm-global/lib/node_modules/plasma-client/node_modules/plasma-utils/src/utils/web3.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Do I miss something?

**Comment by burrrata** [comment] 2019-03-08 03:52
Same. 

Happened when I typed `$ plasma-client`.

The same thing also happened with the [Plasma Chain Operator](https://github.com/plasma-group/plasma-chain-operator) repo when I typed `$ plasma-chain account new`

**Comment by kfichter** [comment] 2019-03-08 18:30
Hi, thanks for the bug report :-) apparently it’s an issue with a new version of utils we pushed. I’m going to make a change so that the client uses the old version and then will double check that everything else is working as intended. Sorry about that!

**Comment by kfichter** [comment] 2019-03-08 19:21
Whoops, nvm. Apparently it's an error in one of our dependencies: https://github.com/ethereum/web3.js/issues/2469

Going to try to get rid of that dep altogether.

**Comment by kfichter** [comment] 2019-03-08 20:01
I’m gonna peg to an older version of the dependency since it’s being removed in the new version of utils anyway. Should fix the issue for now.

**Comment by kfichter** [comment] 2019-03-08 21:02
Just went ahead and pushed a fix to this. Can you try again and let me know if everything is working?

**Comment by desimira** [comment] 2019-03-08 21:13
> Just went ahead and pushed a fix to this. Can you try again and let me know if everything is working?

I've just tried, but get into another error:
```Desimiras-MacBook-Pro:plasma-client desimiramitkova$ plasma-client
[Function: BaseDBProvider]
{ Error: ENOENT: no such file or directory, mkdir '/Users/desimiramitkova/Library/Application Support/io.plasma.group/wallet'
    at Object.fs.mkdirSync (fs.js:905:18)
    at new LevelDBProvider (/usr/local/lib/node_modules/plasma-client/src/services/level-db-provider.js:18:10)
    at DBService.open (/usr/local/lib/node_modules/plasma-client/node_modules/plasma-core/src/services/db/db-service.js:16:16)
    at WalletDB._onStart (/usr/local/lib/node_modules/plasma-client/node_modules/plasma-core/src/services/db/interfaces/wallet-db.js:16:28)
    at WalletDB.start (/usr/local/lib/node_modules/plasma-client/node_modules/plasma-core/src/services/base-service.js:91:16)
    at Plasma.startService (/usr/local/lib/node_modules/plasma-client/node_modules/plasma-core/src/plasma.js:147:21)
    at Plasma.start (/usr/local/lib/node_modules/plasma-client/node_modules/plasma-core/src/plasma.js:175:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/Users/desimiramitkova/Library/Application Support/io.plasma.group/wallet' }
  service:contract Connected to plasma chain: PG-beta.14 +0ms
  service:contract Contract address set: 0x420CB3695da6C251Fc095ACf6440b27eD7d790e9 +0ms
  service:contract Operator endpoint set: operator.plasma.group/api +0ms
(node:18227) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir '/Users/desimiramitkova/Library/Application Support/io.plasma.group/sync/0x420CB3695da6C251Fc095ACf6440b27eD7d790e9'
```

**Comment by kfichter** [comment] 2019-03-08 21:25
Hmmm... @desimira what version of Node are you using?

**Comment by kfichter** [comment] 2019-03-08 21:28
@desimira pushed another version. Can you update and try again?

**Comment by desimira** [comment] 2019-03-09 07:13
@kfichter Yep, I tried again and everything is great now. I am connected. Thanks!

**Comment by burrrata** [comment] 2019-03-10 17:48
Just ran the linux instructions and it's working. Thanks :)

**Comment by kfichter** [comment] 2019-03-10 20:10
Np! Closing this :-)

**Closed by kfichter** 2019-03-10 20:10 UTC
Labels: bug
